options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/zhabkas-bot', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/zhabkas-bot']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy zhabkas \
          --image gcr.io/$PROJECT_ID/zhabkas-bot \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated

images:
  - 'gcr.io/$PROJECT_ID/zhabkas-bot'
